# Generated by Django 3.1.5 on 2021-01-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
